
GET http://localhost:8585/address
###
POST localhost:8585/address/
Content-Type: application/json

{
  "description": "post working hour",
  "name" : "address work hour"
}

###

PUT localhost:8585/address/63b2eeeff0add618721e1a4c
#modify value after address/ with _id get from posted value
Content-Type: application/json

{
 "name": "another Address",
  "description": "put addressss"
}

###
DELETE localhost:8585/address/63b43c10f0add605e7182870
#modify value after address/ with _id you want to be deleted

