
GET http://localhost:8585/abc
###
POST localhost:8585/abc/
Content-Type: application/json

{
  "description": "post ke 4",
  "name" : "test post 4"
}

###

PUT localhost:8585/abc/63a079ac400f361b50a0f666
Content-Type: application/json

{
 "name": "jpo",
  "description": "test update"
}

###




