
GET http://localhost:8585/api/address
###
POST localhost:8585/api/address/
Content-Type: application/json

{
  "description": "post working hour",
  "name" : "address work hour"
}

###

PUT localhost:8585/api/address/63b2eeeff0add618721e1a4c
#modify value after address/ with _id get from posted value
Content-Type: application/json

{
 "name": "another Address",
  "description": "put addressss"
}

###
DELETE localhost:8585/api/address/63c523cc6c02d67c97251bac
#modify value after address/ with _id you want to be deleted

### SignUp Part
POST localhost:8080/api/authentication/signup/
Content-Type: application/json

{
  "username": "userMod",
  "email" : "userMod@email.com",
  "password": "12345678",
  "roles": ["user", "mod"]
}
